export const mockData = [
  {
    orderId: "#001234ABCD",
    category: "Electronic",
    arrivalTime: "7/1/2023",
    weight: "25kg",
    route: "87 Wern Ddu Lane → 15 Vicar Lane",
    fee: "$1,050",
    status: "Delivered",
    origin: "40 Broomfield Place",
    destination: "44 Helland Bridge",
  },
  {
    orderId: "#0023456LKH",
    category: "Furniture",
    arrivalTime: "7/1/2023",
    weight: "50kg",
    route: "40 Broomfield Place → 44 Helland Bridge",
    fee: "$2,200",
    status: "Pending",
    origin: "40 Broomfield Place",
    destination: "44 Helland Bridge",
  },
  {
    orderId: "#0023456LKH",
    category: "Clothing",
    arrivalTime: "7/1/2023",
    weight: "50kg",
    route: "11 Walden Road → 39 Grenoble Road",
    fee: "$800",
    status: "Shipping",
    origin: "40 Broomfield Place",
    destination: "44 Helland Bridge",
  },
  {
    orderId: "#001234ABCD",
    origin: "87 Vern Ddu Lane",
    destination: "15 Vicar Lane",
    category: "Clothing",
    arrivalTime: "7/1/2023",
    weight: "50kg",
    route: "11 Walden Road → 39 Grenoble Road",
    fee: "$800",
    status: "Ongoing",
  },
  {
    orderId: "#00123456LKJ",
    origin: "40 Broomfield Place",
    destination: "44 Helland Bridge",
    category: "Clothing",
    arrivalTime: "7/1/2023",
    weight: "50kg",
    route: "11 Walden Road → 39 Grenoble Road",
    fee: "$800",
    status: "Ongoing",
  },
];
